{% set name = "lamin_utils" %}
{% set version = "0.13.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lamin_utils-{{ version }}.tar.gz
  sha256: 5a772e3588e5027adf01f7d5364f01c371db75c60aec960e35c897a5130f1cf3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.7
    - packaging

test:
  imports:
    - lamin_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/laminlabs/lamin-utils
  summary: Utils for LaminDB and Bionty.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - berombau
