{% set name = "lamin_utils" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lamin_utils-{{ version }}.tar.gz
  sha256: f3973f25166f349a06f1a2a7f7d2b6a4ddc664ef90524a90a00f73762f40c194

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.7
    - packaging

test:
  imports:
    - lamin_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/laminlabs/lamin-utils
  summary: Utils for LaminDB and Bionty.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - berombau
